import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { MY_COOKIE_THEME_KEY } from "@/constants/Variables";
import { THEME, ThemeProvider } from "next-theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get(MY_COOKIE_THEME_KEY)?.value;

  const initTheme =
    themeCookie === THEME.DARK ||
    themeCookie === THEME.LIGHT ||
    themeCookie === THEME.SYSTEM
      ? themeCookie
      : THEME.SYSTEM;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider initialTheme={initTheme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
